
* ncl-mode for Ncar Command Language(NCL)
the original version is downloaded from the following link
http://www.ncl.ucar.edu/Applications/Files/ncl.el.

* ncl.el
This repo was created to serve the el-get. Since I am using NCL mode
day to day I started modifying.  I am not maintainer of ncl.el. I will
submit my changes upstream sometime soon.

* ncl-doc.el
ncl.el is mailnly modified to accommodate ncl-doc.el which is a
major/minor mode to help documentation lookup from ncl website.

The version was bumped up to v0.9x to separate from the original
version. if anyone finds my changes useful and find any bugs
please let me know.  TODO section has details about changes I plan to
implement

* Setup:
put this in your .emacs
#+source: setup
#+begin_src elisp
: (require 'ncl-doc)
: (add-hook 'ncl-mode-hook
:          (lambda ()
:            (ncl-doc-minor-mode 1)))
#+end_src

* Usage:
** M-x ncl-doc-query-at-point ( C-c C-s )
This function does:
   1) It prompts for a string/keyword and collects a given string
   2) It tries to find a URL for the given string
      + If no URL is found, then goes on to search for the given
        string.
      + Displays all search matches in separate buffer category wise.
        In that buffer RET in any search match will call browser for
        take you to that page.
      + If no matches found for a given string it leaves you there

** M-x ncl-doc-query-open  ( C-c C-o )
Use this function you lets you choose from the all keywords ncl-doc
has in its database and takes you to that page.

* Customization:
M-x customize-group RET ncl-doc RET
check out the following variables
 - `ncl-doc-url-base' = defaults to "http://www.ncl.ucar.edu"
   you can change this to any folder if you have downloaded the
   documentation from the NCL website and want read offline.
: (setq ncl-doc-url-base "file:///home/yagnesh/docs/ncl/")

Tip from NCL website FAQ:
:  Is there a way I can download the NCL website documentation so I
:  can access it locally on my machine?
:  TJ Onley pointed out this nice solution. For example, if you just want
:  to download the files under http://www.ncl.ucar.edu/Document, use:
:
:  wget -r -l0  -p -np -nH -k http://www.ncl.ucar.edu/Document/
:
: This will create a directory called "Document", and in that directory,
: you can open the "index.shtml" file with your web browser and have
: access to all the files locally.


 - `ncl-doc-minor-mode-hook'

* TODOS
** NCL MODE
- [X] make font lock work better/faster
- [X] imenu support
  - imenu can directly be used by keyboard (may be with ido or directly)
  - see function: ncl-add-imenu-menu
- [ ] easy menu
- [ ] fixing commenting system
- [ ] fixing indentation

** NCL-DOC mode
a mode to access/assist to read the online documentation from the Ncl
website
- [X] call browser to look documentation of keyword
- [ ] reading docs with in emacs
